### ISSUE TITLE
Fail to get Oauth2.0 using gmail quick start

### ISSUE THREAD

**Issue by iahmedani** [gsuitedevs/node-samples#11]
## Expected Behavior
Generate Code

## Actual Behavior
#Relplaced Path with XXXXX
 var auth = new googleAuth();
             ^

TypeError: googleAuth is not a constructor
    at authorize (C:\XXXXXXXi\quickstart.js:52:14)
    at processClientSecrets (C:\XXXXX\quickstart.js:38:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:528:3)

## Steps to Reproduce the Problem

 Step followed described here:
https://developers.google.com/gmail/api/quickstart/nodejs

## Specifications
Node v9.5.0
OS Windows 10 pro
  - Node version (`node -v`)
  - OS (Mac/Linux/Windows)

**Comment by IshaanRawat** [comment]
@iahmedani Look at the code in the the repo here. [Gmail Quickstart](https://github.com/gsuitedevs/node-samples/tree/master/gmail/quickstart)
Try implementing with that.

**Comment by iahmedani** [comment]
thanks dear for prompt response now it shows new error;

 let oauth2Client = new auth.OAuth2(clientId, clientSecret, redirectUrl);                     ^

TypeError: auth.OAuth2 is not a constructor

node v9.11.0 
windows 10 pro

**Comment by IshaanRawat** [comment]
make the following changes:
try
`let oauth2Client = new google.auth.OAuth2(clientId, clientSecret, redirectUrl);`
instead of
`let oauth2Client = new auth.OAuth2(clientId, clientSecret, redirectUrl);`.

**Comment by erickoledadevrel** [comment]
I've submitted PR #12 which should fix this. Sorry for the confusion.

**Comment by grant** [comment]
Pardon the breakage.
The latest update should fix this OAuth error for the quickstarts.
