### ISSUE TITLE
Shorthand prop name makes quickstart fail

### ISSUE THREAD

**Issue by toasterpic** [gsuitedevs/node-samples#15]
## Expected Behavior
see https://developers.google.com/drive/api/v3/quickstart/nodejs#step_4_run_the_sample

## Actual Behavior
(node:36003) UnhandledPromiseRejectionWarning: TypeError: Cannot destructure property `data` of 'undefined' or 'null'. in quickstart.js line 75.

## Steps to Reproduce the Problem

1. follow https://developers.google.com/drive/api/v3/quickstart/nodejs => failure
2. change line 75 from `}, (err, {data}) => {` to: `}, (err, response) => {` and line 77 from `const files = data.files;` to `const files = response.data.files;` => success    

## Specifications

  - Node version (`node -v`) v8.11.3 (LTS)
  - OS (Mac)

**Comment by grant** [comment]
Thanks for the report.
Will have to not destructure so early in case there is an error.
