### ISSUE TITLE
TypeError: Cannot read property 'auth' of undefined

### ISSUE THREAD

**Issue by Usama-Tahir** [gsuitedevs/node-samples#19]
I am using this quickstart to setup Google Sheets API.
link: https://developers.google.com/sheets/api/quickstart/nodejs

## Actual Behavior
I am getting this error when I run index.js.

```
  const oAuth2Client = new google.auth.OAuth2(
      client_id, client_secret, redirect_uris[0]);
TypeError: Cannot read property 'auth' of undefined
```

## Steps to Reproduce the Problem

  1. simply follow the tutorial.
  1. when I run index.js file using node ., I get the error mentioned above.

## Specifications

  - Node version : 8.11.3
  - OS :Windows

**Comment by erickoledadevrel** [comment]
I'm not able to reproduce this. Which version of the googleapis module do you have installed? Can you post the `require()` used to import that module?

**Comment by grant** [comment]
@Usama-Tahir Did you install `googleapis` before running the sample?

**Comment by grant** [comment]
Closing this inactive issue since it's not reproducible.
Feel free to reopen the issue if this is still persisting.
