### ISSUE TITLE
Error loading client secret file: { Error: ENOENT: no such file or directory, open

### ISSUE THREAD

**Issue by Ladvace** [gsuitedevs/node-samples#24]
## Actual Behavior
Error loading client secret file: { Error: ENOENT: no such file or directory, open

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Node version (`node -v`)
  - OS (Mac/Linux/Windows)

**Comment by grant** [comment]
@Ladvace Please provide more details.
Which sample? Did you download the credentials?

**Comment by grant** [comment]
@Ladvace Can you fill out the template with specific details?

**Comment by grant** [comment]
The error states there's a problem loading the client secrets file.
Looks like this is a problem with the credentials not being set up (which is a required step).
Closing, but feel free to comment here if that's not the case.
