### ISSUE TITLE
The API returned an error: Not Authorized to access this resource/api

### ISSUE THREAD

**Issue by HellaSolutions** [gsuitedevs/node-samples#27]
## Expected Behavior

Lists the first 10 users in the domain.

## Actual Behavior

Outputs

Authorize this app by visiting this url: https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fadmin.directory.user&response_type=code&client_id=1025492374039-7btb479dh06fcqgh5ckuge56av0rfin5.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob
Enter the code from that page here: 4/QQC1oHz9949l53WSHoXEUGtgqEfXYw0Bu-TM-9s 41EnUdX0EZq6FH8
Token stored to token.json
The API returned an error: Not Authorized to access this resource/api

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Node version (`node -v`) v8.11.4
  - OS (Mac/Linux/Windows) Windows 10

**Comment by grant** [comment]
Hi @HellaSolutions,
As the error states, your G Suite account is **not authorized to access this resource/api**. Your G Suite Admin must allow you to access this API.

We describe this in the docs here:
https://developers.google.com/admin-sdk/directory/v1/guides/prerequisites

Let me know if could be made clearer somewhere and we can add a note in the code or docs.
