### ISSUE TITLE
Bootstrap throws error? 

### ISSUE THREAD

**Issue by lillan95** [gsuitedevs/node-samples#29]
## Expected Behavior
It to prompt me to authorize access to google API. 

## Actual Behavior
Error code:
internal/modules/cjs/loader.js:573
    throw err;
    ^

Error: Cannot find module 'C:\DP\delivery_group_webpage'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)

## Steps to Reproduce the Problem

I followed the steps on this tutorial. https://developers.google.com/calendar/quickstart/nodejs
But my directory is quite big and I didn't quite know where to put the index.js and credentials.json file. Tired them in both the maps "app" and "src" but it didn't change the outcome when running node . in terminal. 

## Specifications
  - Angular v6.0
  - Node version v10.0.0
  - OS (Windows)

_____

Thanks for helping me!

**Comment by grant** [comment]
In the docs, we state to use your "working directory" for both files (`credentials.json`, `index.js`).
Let us know if we can make the instructions clearer somehow. Thanks for the help @pistachio05.
