### ISSUE TITLE
Sheets Quick Start Not Working

### ISSUE THREAD

**Issue by jeeeep** [gsuitedevs/node-samples#32]
## Expected Behavior
Run script and be brought to oauth screen that has code you enter on the command line.

## Actual Behavior
Run script and get Error: "Missing required parameter: redirect_uri"

## Steps to Reproduce the Problem

  1. Download file sheets/quickstart/index.js
  2. Create project and download credentials.json and put it in the same directory as index.js
  3. run node index.js and click click

## Specifications

  - Node version (9.3.0)
  - OS (Mac)

**Comment by asrivas** [comment]
Did you make any edits? I just ran this quickstart with node 10 and a test account but couldn't reproduce your issue.
It looks similar to this:
https://stackoverflow.com/questions/32924963/missing-required-parameter-redirect-uri-with-passport-google-oauth

**Comment by pokhriyalvipin** [comment]
hi all,
please help me on this issue
i added a function to run the code and its showing error while running such as:

{ message: 'Request had insufficient authentication scopes.',
       domain: 'global',
       reason: 'forbidden' }


Code is here:
`const fs = require('fs');
const readline = require('readline');
const {google} = require('googleapis');
console.log("its start working...");
// If modifying these scopes, delete token.json.
const SCOPES = ['https://www.googleapis.com/auth/script.projects'];
const TOKEN_PATH = 'token.json';

// Load client secrets from a local file.
fs.readFile('credentials.json', (err, content) => {
  if (err) return console.log('Error loading client secret file:', err);
  console.log("content::::",JSON.parse(content));
  // Authorize a client with credentials, then call the Google Apps Script API.
  authorize(JSON.parse(content), callAppsScript);
});

/**
 * Create an OAuth2 client with the given credentials, and then execute the
 * given callback function.
 * @param {Object} credentials The authorization client credentials.
 * @param {function} callback The callback to call with the authorized client.
 */
function authorize(credentials, callback) {
  const {client_secret, client_id, redirect_uris} = credentials.installed;
  const oAuth2Client = new google.auth.OAuth2(
      client_id, client_secret, redirect_uris[0]);

  // Check if we have previously stored a token.
  fs.readFile(TOKEN_PATH, (err, token) => {
    console.log("Token path:::",TOKEN_PATH);
    if (err) return getAccessToken(oAuth2Client, callback);
    oAuth2Client.setCredentials(JSON.parse(token));
    callback(oAuth2Client);
  });
}

/**
 * Get and store new token after prompting for user authorization, and then
 * execute the given callback with the authorized OAuth2 client.
 * @param {google.auth.OAuth2} oAuth2Client The OAuth2 client to get token for.
 * @param {getEventsCallback} callback The callback for the authorized client.
 */
function getAccessToken(oAuth2Client, callback) {
  const authUrl = oAuth2Client.generateAuthUrl({
    access_type: 'offline',
    scope: SCOPES,
  });
  console.log('Authorize this app by visiting this url:', authUrl);
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  rl.question('Enter the code from that page here: ', (code) => {
    rl.close();
    oAuth2Client.getToken(code, (err, token) => {
      if (err) return console.error('Error retrieving access token', err);
      oAuth2Client.setCredentials(token);
      // Store the token to disk for later program executions
      fs.writeFile(TOKEN_PATH, JSON.stringify(token), (err) => {
        if (err) console.error(err);
        console.log('Token stored to', TOKEN_PATH);
      });
      callback(oAuth2Client);
    });
  });
}

/**
 * Creates a new script project, upload a file, and log the script's URL.
 * @param {google.auth.OAuth2} auth An authorized OAuth2 client.
 */
function callAppsScript(auth) {
  const script = google.script({version: 'v1', auth});
  script.projects.create({
    resource: {
      title: 'My Script',
    },
  }, (err, res) => {
    if (err) return console.log(`The API create method returned an error: ${err}`);
    script.projects.updateContent({
      scriptId: res.data.scriptId,
      auth,
      resource: {
        files: [{
          name: 'hello',
          type: 'SERVER_JS',
          source: 'function myApp(){\n var form = FormApp.create(\'New Form\'); \n var item = form.addCheckboxItem(); \n item.setTitle(\'What condiments would you like on your hot dog?\');\n item.setChoices([item.createChoice(\'Ketchup\'),\n item.createChoice(\'Mustard\'),\n item.createChoice(\'Relish\')]);\n}',
        }, {
          name: 'appsscript',
          type: 'JSON',
          source: '{\"timeZone\":\"America/New_York\",\"exceptionLogging\":' +'\"CLOUD\", \"oauthScopes\":[\"https://www.googleapis.com/auth/forms\",\"https://www.googleapis.com/auth/drive\",\"https://www.googleapis.com/auth/forms.currentonly\",\"https://www.googleapis.com/auth/spreadsheets\",\"https://www.googleapis.com/auth/analytics.readonly\",\"https://www.googleapis.com/auth/spreadsheets.readonly\"]}',
        }],
      },
    }, {}, (err, res) => {
      if (err) return console.log(`The API updateContent method returned an error: ${err}`);
      console.log(`https://script.google.com/d/${res.data.scriptId}/edit`);
      if(res.data.scriptId){
        script.scripts.run({
        scriptId:res.data.scriptId,
        auth,
        resource: {
        "function": 'myApp',
        "parameters": [res.data.scriptId],
        "sessionState": '',
        "devMode":true
      },
      })
    }
    });
  });
}`

**Comment by grant** [comment]
Closed due to inactivity.
