### ISSUE TITLE
I got a ur and it did not lead anywhere

### ISSUE THREAD

**Issue by johnmorrisbeck** [gsuitedevs/node-samples#33]
## Expected Behavior
type .node as per this page:https://developers.google.com/drive/api/v3/quickstart/nodejs

get access to my own google drive account

## Actual Behavior
typing .node gives me a long oath url that leads nowhere

## Steps to Reproduce the Problem

  1.Follow the instructions on the page
  1.
  1.

## Specifications

  - Node version (`node -v`)
v8.10.0  
  - OS (Mac/Linux/Windows)
xubuntu

**Comment by grant** [comment]
> that leads nowhere
What do you see?

**Comment by takacspeter** [comment]
`Error: invalid_request

Missing required parameter: redirect_uri`

**Comment by grant** [comment]
It looks like your OAuth client was deleted.
Please read more about OAuth clients here, and be sure the client is in your Cloud Project that you used in step 1 is current.

Useful links:
https://stackoverflow.com/questions/39052052/restore-deleted-google-oauth-client-app-for-production-system
https://cloud.google.com/resource-manager/docs/creating-managing-projects?hl=en&visit_id=636799807082265466-2519089901&rd=1#restoring_a_project
