### ISSUE TITLE
quickstart sample for Gsuite admin sdk-Directory api to list all users in my domain in nodejs

### ISSUE THREAD

**Issue by AnilRo-Kore** [gsuitedevs/node-samples#37]
## Expected Behavior
I suspect to retrieve all the users with the domain

## Actual Behavior
I'm getting Domain not found  error.

## Steps to Reproduce the Problem

  1. I enabled the Directory api access in console.
 2. I tried to access the "https://developers.google.com/admin-sdk/directory/v1/reference/users/list" API with my personal account.

## Specifications

  I'm trying with nodejs sample.

**Comment by erickoledadevrel** [comment]
I'm not clear what the problem you are running into is. The quickstart requires a G Suite admin account to run, and won't work in personal gmail.com accounts.
