### ISSUE TITLE
Google Sheets API v4 not generating authorization code

### ISSUE THREAD

**Issue by rahuliet** [gsuitedevs/node-samples#39]
## Expected Behavior
Code should get generated when URL is hit from browser

## Actual Behavior
**When below URL is hit it gives me 404 error**
https://accounts.google.com/o/oauth2/v2%20/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fspread%20sheets.readonly&response_type=code&client_id=653732879398-bd93as2icshrmu0soou6ro%20g8nv6cdhc3.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%20%3Aoob

## Steps to Reproduce the Problem

  1.Go to URL: https://accounts.google.com/o/oauth2/v2%20/auth?access_type=offline&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fspread%20sheets.readonly&response_type=code&client_id=653732879398-bd93as2icshrmu0soou6ro%20g8nv6cdhc3.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%20%3Aoob
  
## Specifications

  - Node version (`node -v`) - v 8.9.3
  - OS (Mac/Linux/Windows) - windows 7

**Comment by erickoledadevrel** [comment]
It looks like some space characters (`%20`) are getting inserted into your URL. I just re-ran the quickstart and it didn't happen for me, so it might be particular to the command line console you are using. Please check the URL after you copy it from the console to ensure that there are no extra spaces.

**Comment by rahuliet** [comment]
yup it was some spacing issue on windows CMD
