### ISSUE TITLE
Provide examples that not use env variables

### ISSUE THREAD

**Issue by SkeLLLa** [gsuitedevs/node-samples#41]
In order to make examples robust and more useful please consider adding examples that shows how to use library without providing magic env variables, but using options to provide credentials, for example, and so on.

**Comment by grant** [comment]
We don’t use env variables. What do you mean “for example, and so on”?

What do you want to see in which specific samples?

**Comment by SkeLLLa** [comment]
From docs:
```
 // This method looks for the GCLOUD_PROJECT and GOOGLE_APPLICATION_CREDENTIALS
 // environment variables.
```

```
async function main () {
 
  // This method looks for the GCLOUD_PROJECT and GOOGLE_APPLICATION_CREDENTIALS
  // environment variables.
  const auth = await google.auth.getClient({
    // Scopes can be specified either as an array or as a single, space-delimited string.
    scopes: ['https://www.googleapis.com/auth/compute']
  });
 
  // obtain the current project Id
  const project = await google.auth.getProjectId();
 
  // Fetch the list of GCE zones within a project.
  const res = await compute.zones.list({ project, auth });
  console.log(res.data);
}
```

**Comment by grant** [comment]
Can you be more specific?
That sample is about google compute engine, not G Suite.
Could you answer the above two questions?

**Comment by erickoledadevrel** [comment]
You seem to be using the code sample in the `README` for the Google APIs Node.js library:

https://github.com/googleapis/google-api-nodejs-client/blob/master/README.md#service-to-service-authentication

The samples in this repo use that library, but don't use environment variables.
