### ISSUE TITLE
Error: No access, refresh token or API key is set.

### ISSUE THREAD

**Issue by paul019** [gsuitedevs/node-samples#44]
I followed [this quickstart guide](https://developers.google.com/sheets/api/quickstart/nodejs) and got the follwing error after running `node .`:
`The API returned an error: Error: No access, refresh token or API key is set.`

## Specifications

  - Node version: v8.10.0
  - OS: MacOS

**Comment by erickoledadevrel** [comment]
Some folks have reported success changing
```js
const sheets = google.sheets({version: 'v4', auth});
```
to
```js
const sheets = google.sheets({version: 'v4', auth: auth});
```
Does that help?

**Comment by paul019** [comment]
@SamarthaKV29 You sent me a link to a setup guide for the Google calendar API. I want to use the Google Spreadsheet API and followed the according quick start guide. So your link unfortunately doesn't help me. Do you have any other tip for me?

@erickoledadevrel I've also tried out your idea to solve my issue, but it didn't work: After changing `auth` to `auth: auth` the issue still persisted.

**Comment by erickoledadevrel** [comment]
It looks like this error occurs when a file called `token.json` exists but doesn't actually contain a stored OAuth token. Please delete `token.json` and re-run the code.
