### ISSUE TITLE
Quickstart: ENABLE THE GOOGLE SLIDES API, not working

### ISSUE THREAD

**Issue by ebdrup** [gsuitedevs/node-samples#45]
## Expected Behavior
in https://developers.google.com/slides/quickstart/nodejs
- Clicking "ENABLE THE GOOGLE SLIDES API" gives me credentials.json or guides me how to get them

## Actual Behavior

- Clicking "ENABLE THE GOOGLE SLIDES API" gives error:

![image](https://user-images.githubusercontent.com/899914/49379934-bb607b80-f710-11e8-9fb5-61f359474939.png)

From the console
![image](https://user-images.githubusercontent.com/899914/49379989-dc28d100-f710-11e8-8b32-5f710b2765c7.png)
(I couldn't copy all of the message, as there is a key in the URL that I don't know if is sensitive)

## Steps to Reproduce the Problem

  1. Go to: https://developers.google.com/slides/quickstart/nodejs in 
  1. Click "ENABLE THE GOOGLE SLIDES API"

## Specifications

  - Chrome Version 70.0.3538.110 (Official Build) (64-bit) on OSX Mojave V10.14.1

**Comment by erickoledadevrel** [comment]
Thanks for reporting this error. We've reverted a recent change and the problem should be fixed now.
