### ISSUE TITLE
Can't run the example code.

### ISSUE THREAD

**Issue by mlyticsAdamGe** [gsuitedevs/node-samples#48]
## Expected Behavior
run the example code succeed.

## Actual Behavior
I got an error:
TypeError: Cannot destructure property `client_secret` of 'undefined' or 'null'.

## Steps to Reproduce the Problem

  1. download credentials.json file
  1. run example code
  1. got error

## Specifications
no

Did the credential.json change format ? Or just cause I didn't setting some field for the account?

9.3  - Node version (`node -v`)
Mac  - OS (Mac/Linux/Windows)

**Comment by erickoledadevrel** [comment]
Did you download the `credentials.json` file using the button in the quickstart web page? If not, please ensure you created a client ID of the type "Other".

**Comment by pkafei** [comment]
I got the same error and I did download the `credentials.json` file. I'm currently using node v11.3.0.

**Comment by pkafei** [comment]
Got the example code to work. My json file was slightly different than the credential file generated by `Enable Drive Button`. I was initially passing the json file created by https://console.developers.google.com/apis/dashboard.

**Comment by sapanburman** [comment]
its works for me i hope also works for you 

{"installed":{"client_id":"xxxxxxxxxxxxx.apps.googleusercontent.com",
"project_id":"xxxxxxxxxxxx",
"auth_uri":"https://accounts.google.com/o/oauth2/auth",
"token_uri":"https://oauth2.googleapis.com/token",
"auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
"client_secret":"xxxxxxxxxxxxxxxxx","redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]}} 
1) replace "web" to "installed" .
2)add "redirect_uris":["urn:ietf:wg:oauth:2.0:oob","http://localhost"]

**Comment by erickoledadevrel** [comment]
The quickstarts require a client ID of type "Other", and other client types will fail.
