### ISSUE TITLE
Error retrieving access token

### ISSUE THREAD

**Issue by boring2** [gsuitedevs/node-samples#49]
## Expected Behavior
get token and write to token.json

## Actual Behavior
Error retrieving access token { Error: write EPROTO 4508878272:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252

## Specifications
  - Node version (10.14.2)
  - OS (Mac)

**Comment by aleguern** [comment]
Same with me !

**Comment by erickoledadevrel** [comment]
This appears to be a problem in the underlying axios library:

https://github.com/axios/axios/issues/1877

According to that issue you can resolve it by updating the dependency to a newer version.
