### ISSUE TITLE
Missing required parameter: redirect_uri

### ISSUE THREAD

**Issue by vseva** [gsuitedevs/node-samples#53]
## Expected Behavior
I got a code to write in console

## Actual Behavior
I got an error "Error: invalid_requestMissing required parameter: redirect_uri"

## Steps to Reproduce the Problem

Go down all first three steps from tutorial https://developers.google.com/sheets/api/quickstart/nodejs and click the link after enter command "node ." and see the error.

## Specifications

  - Node version v6.9.1
  - OS Mac 10.14.1
  - Browser Chrome 71

**Comment by erickoledadevrel** [comment]
Ensure you are using an OAuth client ID of type "Other". This is the type created for you if you download credentials via the button in the quickstart instructions.
