### ISSUE TITLE
Missing return statement?

### ISSUE THREAD

**Issue by therealgilles** [gsuitedevs/node-samples#55]
The if statement below only displays the error to the console. Isn't a return statement missing? Also using err when it was already used right above in the same scope is not a good idea.

https://github.com/gsuitedevs/node-samples/blob/385b833e07d90cd23c05121c1624a35bf2ec39ac/sheets/quickstart/index.js#L78

**Comment by erickoledadevrel** [comment]
Whoops! Looks like we dropped the return there. It should be `if (err) return console.error(err);` I also agree that reusing `err` isn't the best.

Would you be willing to create a PR to fix these?
