### ISSUE TITLE
Unable to get the quickstart to work with service account key file

### ISSUE THREAD

**Issue by thxmike** [gsuitedevs/node-samples#56]
## Expected Behavior
To modify the NodeJs quickstart: https://developers.google.com/admin-sdk/directory/v1/quickstart/nodejs to work with a service account key file

## Actual Behavior
Errors

## Steps to Reproduce the Problem

  1. 
  1.Modify the Authorize to use a key file in the Oauth2 constructor
  1.

## Specifications

  - Node version (`node -v`) - 10.14
  - OS (Mac/Linux/Windows) Mac

**Comment by erickoledadevrel** [comment]
These samples are designed for 3-legged user auth. Please refer to the Google APIs Node.js Client Library documentation for information on how to use service accounts:

https://github.com/googleapis/google-api-nodejs-client#service-to-service-authentication
