### ISSUE TITLE
Entering code 

### ISSUE THREAD

**Issue by rajeev99342** [gsuitedevs/node-samples#57]
## Expected Behavior
what to put on cmd ->"Enter the code from that page here"

## Actual Behavior

what to give code 
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Node version (`node -v`)
  - OS (Mac/Linux/Windows)

**Comment by rajeev99342** [comment]
during executing it asked to enter a code. what to give? thanks in advance

**Comment by erickoledadevrel** [comment]
When you visit the URL that was printed to the console, and complete the OAuth flow, you will recieve the authorization code.
