### ISSUE TITLE
Cannot read property 'OAuth2' of undefined

### ISSUE THREAD

**Issue by IshaanRawat** [gsuitedevs/node-samples#6]
In the Google sheets api sample code:
https://github.com/gsuitedevs/node-samples/blob/e426bd6af84904ea49ebd043787659936264727a/sheets/quickstart/index.js#L20

## Expected Behavior
The following should be working properly.
`const google = require('googleapis');`
`const OAuth2Client = google.auth.OAuth2;`

## Actual Behavior
Instead, it is showing 
`Cannot read property 'OAuth2' of undefined`

## Steps to Reproduce the Problem

  1. Just create a quickstart.js with the code linked above.
  1. Install required packages.
  1. Run `node quickstart.js`.

## Solution
After debugging the code, I found out that it is using the google property in the google variable that we required from googleapis. This bug was resulting in the undefined behavior as `google.auth` is not defined. What actually defined is `google.google.auth`.
So what I did was extract the google property directly be using ES6 destructuring which fixed this issue and all the further issues which were created by it.
`const {google} = require('googleapis');`

## Specifications

  - Node version - v8.10.0
  - OS - Linux(Ubuntu v16.04)

**Comment by iwin2471** [comment]
I already fix this problem at #3 
but I didn't mention about this prob... sorry

**Comment by IshaanRawat** [comment]
No worries. :+1: 
By the way, this problem is still there in many gsuitedev/node-samples quickstart codes and READMEs. If you want I can fix them on all the places.

**Comment by IshaanRawat** [comment]
@grant I found this issue on many of the Node.js documentation on the Google website also. I would be happy to contribute to those also.

**Comment by grant** [comment]
Thanks @paigekehoe.
Looks like I haven't published the updated GitHub snippets for all the pages with changes in the above PR.
I will leave this issue open until I do.

**Comment by kielypatrick** [comment]
Thanks, good spot!

**Comment by grant** [comment]
Published.
