### ISSUE TITLE
 error_description: 'Malformed auth code.'

### ISSUE THREAD

**Issue by s2pedutech** [gsuitedevs/node-samples#60]
## Expected Behavior
Authorize gmail api

## Actual Behavior

 error_description: 'Malformed auth code.'

## Steps to Reproduce the Problem

  1. Download the config file in root directory
  2. node .
  3. paste the secret key

## Specifications

  - Node version (`node -v`) 10.14.2
  - OS (Mac/Linux/Windows)
Windows

**Comment by erickoledadevrel** [comment]
Please make sure you are copying the authorization code completely, without any extra whitespace.
