### ISSUE TITLE
Uncaught TypeError: Expected `input` to be a `Function` or `Object`, got `undefined`

### ISSUE THREAD

**Issue by jemiris** [gsuitedevs/node-samples#62]
Hi,
I have got the issue while accessing the google sheet API. I tried to Google Sheets API (https://developers.google.com/sheets/api/quickstart/nodejs). And made it as npm package while tried to include the package in new project. i got an issue

`Uncaught TypeError: Expected input to be a Function or Object, got undefined at module.exports (index.js?2556:45) at eval (index.js?f447:22) at Object../node_modules/gtoken/build/src/index.js (app.js:5720) at __webpack_require__ (app.js:724) at fn (app.js:101) at eval (jwtclient.js?d465:63) at Object../node_modules/google-auth-library/build/src/auth/jwtclient.js (app.js:3154) at __webpack_require__ (app.js:724) at fn (app.js:101) at Object.eval (googleauth.js?0a40:73)`

Please fix the issue
Ref: https://stackoverflow.com/questions/54468809/what-is-causing-typeerror-expected-input-to-be-a-function-or-object-issue/54920596#54920596

**Comment by erickoledadevrel** [comment]
It seems like you already opened an issue on the library itself:

https://github.com/googleapis/google-api-nodejs-client/issues/1620

This issue likely isn't related to the Google Sheets API, so closing this copy in favor of that one.
