### ISSUE TITLE
Token Error: The request is missing a valid API key

### ISSUE THREAD

**Issue by mingyuea** [gsuitedevs/node-samples#63]
## Expected Behavior
To return the requested data

## Actual Behavior
Returns an error saying a valid API key is required, even though a OAuth2 token has already been attached

## Steps to Reproduce the Problem

  1. Create OAuth Credentials, get code after user authorization, get token using code
  2. `Use oAuth2Client.setCredentials(JSON.parse(token))` to set credentials
  3. Make a request using ```google.sheets({version: 'v4', oAuth2Client}).values.get({spreadsheetId: '...', range: '...',})```

## Specifications

  - Node version (`node -v`) 10.14.0
  - OS (Mac/Linux/Windows) Windows 10 

I've followed the example on the Google Sheets API for using OAuth2 for authentication of requests. However, instead of a plain Node app, I want to use it as an Express app. I managed to set up my own credentials, get the code for the user, get the token for a user from the code, and write the token to a 'token.json' file. 

However, whenever I make the call to get spreadsheet data, like so:
```
app.get('/home', async (req, res) => {
	let oAuth2Client = () => {
        let credentials;

	try{
		let content = await readFile('credentials.json');
		console.log(content);
		credentials = JSON.parse(content);
	} catch(err){
		let errMsg = 'Error loading client secret file: ' + err;
		console.log(errMsg);
		res.send({"actionSuccess": false, "error:" : errMsg});
	}

	let {client_secret, client_id, redirect_uris} = credentials.web;
	let oAuth2Client = new google.auth.OAuth2(client_id, client_secret, redirect_uris[0]);
	    
	return oAuth2Client;
};
	let token;

	try{
		token = await readFile('token.json');
	} catch (err){
		let errMsg = "Error while trying to retrieve access token: " + err;
		console.log(errMsg);
		res.send({"actionSuccess": false, "error:" : errMsg});
	}

	//console.log(token, 'is token', oAuth2Client, 'is oauth');
	//console.log('before', oAuth2Client);
	await oAuth2Client.setCredentials(JSON.parse(token));
	//console.log('after', oAuth2Client);

	const sheets = google.sheets({version: 'v4', oAuth2Client});
	console.log(sheets);
	sheets.spreadsheets.values.get({
	    spreadsheetId: '...',
	    range: '...',
	}, (err, response) => {
	    if (err){
	    	let errMsg = 'The API returned an error: ' + err;
	    	console.log(errMsg);
	    	res.send({"actionSuccess": false, "error:" : errMsg})
	    }
	    console.log(response);

	    const rows = response.data.values;
	    if (rows.length) {
	    	res.send({"actionSuccess": true, "data": rows});
	    }
	    else {
	    	res.send({"actionSuccess": false, "error": "No data found"});
	    }
	  })
})
```

I always get the error: 

> The API returned an error: Error: The request is missing a valid API key.

I check and my OAuth2 is CLEARLY there, so now I'm pulling my hair out wondering why I need this API key, and WHERE I'm supposed to suddenly get this API key? I thought, at first, maybe my credentials and tokens were wrong, but I tried the sample index.js file for the Google Sheets quickstart, and it works fine. So how come when I use it in an Express server it pops up with this error?

**Comment by mingyuea** [comment]
I looked at other similar access token errors, saw someone recommend putting: 
`const sheets = google.sheets({version: 'v4', auth: oAuth2Client})`
which worked

**Comment by jplemoussu** [comment]
THANK YOU @mingyuea mingyuea ! 

Spent hours pulling my hair on the exact same problem until I find your solution.

**Comment by owencm** [comment]
Same - refactored the sample code and made this mistake! Thanks @mingyuea!

**Comment by zjost** [comment]
Why?!?!?!?

**Comment by Robot72** [comment]
Thank you!

**Comment by JamesAyres16** [comment]
Thank you! Saved me hours of troubleshooting.
