### ISSUE TITLE
Cannot destructure property `client_secret` of 'undefined' or 'null'.

### ISSUE THREAD

**Issue by gakeko2018** [gsuitedevs/node-samples#64]
## Expected Behavior
expected the script to work.

## Actual Behavior
I got an error.
  const {client_secret, client_id, redirect_uris} = credentials.installed;
         ^

TypeError: Cannot destructure property `client_secret` of 'undefined' or 'null'.
    at authorize (C:\Users\Mustafa Aygün\Desktop\code\emailer_test\quickstart.js:26:65)
    at fs.readFile (C:\Users\Mustafa Aygün\Desktop\code\emailer_test\quickstart.js:16:3)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Node version (`node -v`)
  - OS (Mac/Linux/Windows)

**Comment by bruno1407** [comment]
Same problem ! If someone have the solution, will be happy :)

**Comment by taprootalaska** [comment]
I was having the same issue...not sure if this is the "best" solution...but it works.

• delete
    `const {client_secret, client_id, redirect_uris} = credentials.installed;`

• replace with:
    `var client_secret = credentials.client_secret;
     var client_id = credentials.client_id;
     var redirect_uris = credentials.redirect_uris;`

• resulting in the following authorize function:
    `function authorize(credentials, callback) {
     var client_secret = credentials.client_secret;
     var client_id = credentials.client_id;
     var redirect_uris = credentials.redirect_uris;

  const oAuth2Client = new google.auth.OAuth2(
      client_id, client_secret, redirect_uris);

  // Check if we have previously stored a token.
  fs.readFile(TOKEN_PATH, (err, token) => {
    if (err) return getAccessToken(oAuth2Client, callback);
    oAuth2Client.setCredentials(JSON.parse(token));
    callback(oAuth2Client);
  });
}`

**Comment by nmahajanoii** [comment]
var clientSecret = credentials.installed.client_secret; In this line credentials is pointing to client_secret.json so the first key has to be "installed". In my case the key was "web" and that was causing the error. I just renamed the key "web" to "installed".

**Comment by codarbind** [comment]
> var clientSecret = credentials.installed.client_secret; In this line credentials is pointing to client_secret.json so the first key has to be "installed". In my case the key was "web" and that was causing the error. I just renamed the key "web" to "installed".

this worked for me. however, the domain I registered the API with is not yet live, I just want to test out GMAIL API, is there a way I can proceed with the testing, please. Thanks

**Comment by vela91** [comment]
> var clientSecret = credentials.installed.client_secret; In this line credentials is pointing to client_secret.json so the first key has to be "installed". In my case the key was "web" and that was causing the error. I just renamed the key "web" to "installed".

that's no work for my, the same issue but .web instead .installed

**Comment by vela91** [comment]
> 

thanks that was the only way to fix my issue

**Comment by vela91** [comment]
> I was having the same issue...not sure if this is the "best" solution...but it works.
> 
> • delete `const {client_secret, client_id, redirect_uris} = credentials.installed;`
> 
> • replace with: `var client_secret = credentials.client_secret; var client_id = credentials.client_id; var redirect_uris = credentials.redirect_uris;`
> 
> • resulting in the following authorize function: `function authorize(credentials, callback) { var client_secret = credentials.client_secret; var client_id = credentials.client_id; var redirect_uris = credentials.redirect_uris;
> 
> const oAuth2Client = new google.auth.OAuth2( client_id, client_secret, redirect_uris);
> 
> // Check if we have previously stored a token. fs.readFile(TOKEN_PATH, (err, token) => { if (err) return getAccessToken(oAuth2Client, callback); oAuth2Client.setCredentials(JSON.parse(token)); callback(oAuth2Client); }); }`


thanks that was the only way to fix my issue
