### ISSUE TITLE
Google Docs Node.js Quickstart uses wrong version number

### ISSUE THREAD

**Issue by pparke** [gsuitedevs/node-samples#68]
## Expected Behavior
Should be able to successfully run the code after following the instructions.

## Actual Behavior
The wrong `googleapis` version is installed and the code fails with
```
TypeError: google.docs is not a function
```

## Steps to Reproduce the Problem

  1. Follow the directions in https://developers.google.com/docs/api/quickstart/nodejs

## Specifications

  - Node version 11.0.0
  - OS (Mac)

Step 2 which currently reads `npm install googleapis@27 --save` should probably read `npm install googleapis --save`

**Comment by sqrrrl** [comment]
Thanks for catching this. Just updated the docs to the correct minimum version for using the Docs API.
