### ISSUE TITLE
Not receiving  client_secret.json

### ISSUE THREAD

**Issue by mikiper98** [gsuitedevs/node-samples#69]
After i run `node .` i followed the steps but at the end it didn't downloaded any file.

**Comment by grant** [comment]
Which sample are you following?

Did you set up the quickstart properly?

Example:
https://developers.google.com/slides/quickstart/nodejs

**Comment by mikiper98** [comment]
I already solved the problem, basically i was i didn't understood that i had to use the file credential.json and rename it for my application, instead i was expecting to receive another file somehow....
I'm new to this type of stuff -.-
anyway thanks for the help
