### ISSUE TITLE
404. That’s an error.

### ISSUE THREAD

**Issue by nhaslina8** [gsuitedevs/node-samples#70]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Node version (`node -v`)
  - OS (Mac/Linux/Windows)

**Comment by nhaslina8** [comment]
i got url to run like here
![error](https://user-images.githubusercontent.com/22955153/55791128-6a162d80-5af0-11e9-8307-5737564cca7e.jpg)

**Comment by nhaslina8** [comment]
then i got this as result.. why happened?
![results](https://user-images.githubusercontent.com/22955153/55791168-7f8b5780-5af0-11e9-8035-477c7258ea91.jpg)

**Comment by erickoledadevrel** [comment]
Usually the cause of errors like these are strange whitespace characters in the URL, that can occur when you copy the URL in some consoles. Please verify there is no whitespace in the URL and try again.
