### ISSUE TITLE
URL is not a constructor

### ISSUE THREAD

**Issue by rishita1999** [gsuitedevs/node-samples#75]
## Expected Behavior
url copied to the command line and should not give any error and should be authenticated.

## Actual Behavior
when i paste the authorization code, it showing error that url is not a constructor.

## Steps to Reproduce the Problem

  1.first i run the command node.
  2. then it shows a url, go to that and copy the code which comes there
  3. when i paste the code then it shows the error

## Specifications

  - Node version (`node -v`)
  - OS (Mac/Linux/Windows)

**Comment by erickoledadevrel** [comment]
Please include the full exception and/or stack trace.

**Comment by sqrrrl** [comment]
And which sample was run.

**Comment by rishita1999** [comment]
![err](https://user-images.githubusercontent.com/33202758/57391671-d75ec200-7173-11e9-94e9-1f814983b5c5.png)
this error is showing..



and this code is run by me
const fs = require('fs');
const readline = require('readline');
const {google} = require('googleapis');
const url = require('url');
const myURL =
  url.parse('https://localhost:8080');

// If modifying these scopes, delete token.json.
const SCOPES = ['https://www.googleapis.com/auth/calendar.readonly'];
// The file token.json stores the user's access and refresh tokens, and is
// created automatically when the authorization flow completes for the first
// time.
const TOKEN_PATH = 'token.json';

// Load client secrets from a local file.
fs.readFile('credentials.json', (err, content) => {
  if (err) return console.log('Error loading client secret file:', err);
  // Authorize a client with credentials, then call the Google Calendar API.
  authorize(JSON.parse(content), listEvents);
});

/**
 * Create an OAuth2 client with the given credentials, and then execute the
 * given callback function.
 * @param {Object} credentials The authorization client credentials.
 * @param {function} callback The callback to call with the authorized client.
 */
function authorize(credentials, callback) {
  const {client_secret, client_id, redirect_uris} = credentials.installed;
  const oAuth2Client = new google.auth.OAuth2(
      client_id, client_secret, redirect_uris[0]);

  // Check if we have previously stored a token.
  fs.readFile(TOKEN_PATH, (err, token) => {
    if (err) return getAccessToken(oAuth2Client, callback);
    oAuth2Client.setCredentials(JSON.parse(token));
    callback(oAuth2Client);
  });
}

/**
 * Get and store new token after prompting for user authorization, and then
 * execute the given callback with the authorized OAuth2 client.
 * @param {google.auth.OAuth2} oAuth2Client The OAuth2 client to get token for.
 * @param {getEventsCallback} callback The callback for the authorized client.
 */
function getAccessToken(oAuth2Client, callback) {
  const authUrl = oAuth2Client.generateAuthUrl({
    access_type: 'offline',
    scope: SCOPES,
  });
  console.log('Authorize this app by visiting this url:', authUrl);
  const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout,
  });
  rl.question('Enter the code from that page here: ', (code) => {
    rl.close();
    oAuth2Client.getToken(code, (err, token) => {
      if (err) return console.error('Error retrieving access token', err);
      oAuth2Client.setCredentials(token);
      // Store the token to disk for later program executions
      fs.writeFile(TOKEN_PATH, JSON.stringify(token), (err) => {
        if (err) return console.error(err);
        console.log('Token stored to', TOKEN_PATH);
      });
      callback(oAuth2Client);
    });
  });
}

/**
 * Lists the next 10 events on the user's primary calendar.
 * @param {google.auth.OAuth2} auth An authorized OAuth2 client.
 */
function listEvents(auth) {
  const calendar = google.calendar({version: 'v3', auth});
  calendar.events.list({
    calendarId: 'primary',
    timeMin: (new Date()).toISOString(),
    maxResults: 10,
    singleEvents: true,
    orderBy: 'startTime',
  }, (err, res) => {
    if (err) return console.log('The API returned an error: ' + err);
    const events = res.data.items;
    if (events.length) {
      console.log('Upcoming 10 events:');
      events.map((event, i) => {
        const start = event.start.dateTime || event.start.date;
        console.log(`${start} - ${event.summary}`);
      });
    } else {
      console.log('No upcoming events found.');
    }
  });
}

**Comment by sqrrrl** [comment]
What version of node are you using? From the error, I'm guessing something earlier than 6.13.x since that's when the URL constructor was added.

If you are on 6.x, please upgrade. 6.x is no longer supported by the node community.

**Comment by rishita1999** [comment]
its working when i upgrade my version..
