### ISSUE TITLE
Quickstart google.calendar init function broken

### ISSUE THREAD

**Issue by pbakaus** [gsuitedevs/node-samples#82]
In https://developers.google.com/calendar/quickstart/nodejs, there's this line:

```
const calendar = google.calendar({version: 'v3', auth});
```

which isn't valid JS. I'm guessing it should be:

```
const calendar = google.calendar({version: 'v3', auth: auth });
```

**Comment by erickoledadevrel** [comment]
This is a valid syntax in ES6 (AKA ES2015):

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#New_notations_in_ECMAScript_2015
https://dev.to/sarah_chima/enhanced-object-literals-in-es6-a9d
