### ISSUE TITLE
Error loading client secret file in Google Calendar API

### ISSUE THREAD

**Issue by ValeMP** [gsuitedevs/node-samples#89]
## Expected Behavior
When I follow the instruction in https://developers.google.com/calendar/quickstart/nodejs, I expected that the API is running without problems.

## Actual Behavior
When I do the last step, it show the following error:
Error loading client secret file: [Error: ENOENT: no such file or directory, open 'credentials.json'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: 'credentials.json'
}

## Steps to Reproduce the Problem

  1. Write 'npm install googleapis@39 --save' in the terminal of Visual Studio Code
  2. Save the index.js with the content of the page.
  3. Write 'node .' in the terminal of Visual Studio Code and then it show the error.

## Specifications

  - Node version (v12.13.1)
  - OS (Mac/Linux/Windows)
  - Visual Studio Code
  - Working in one file.

**Comment by sqrrrl** [comment]
Appears you did not fully complete step 1 in the quickstart. Please verify you followed instructions correctly and re-open if there's still an issue.
