### ISSUE TITLE
Cannot destructure property 'client_secret' of 'credentials.installed' as it is undefined.

### ISSUE THREAD

**Issue by JeremiahKoeiman** [gsuitedevs/node-samples#92]
## Expected Behavior
Get an URL to authenticate google account

## Actual Behavior
`const {client_secret, client_id, redirect_uris} = credentials.installed;
           ^

TypeError: Cannot destructure property 'client_secret' of 'credentials.installed' as it is undefined.
    at authorize (D:\Anonymous mail\anonymous-mail\backend\functions\gmail.js:26:12)
    at D:\Anonymous mail\anonymous-mail\backend\functions\gmail.js:16:5
?[90m    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)?[39m
`

## Steps to Reproduce the Problem
?

## Specifications

  - Node version 12.16.1
  - OS (Windows)

**Comment by shaikh-amaan-fm** [comment]
In the code change "credentials.installed" to "credentials.web"

**Comment by timuptocreate** [comment]
for me the same issue. it does not work

**Comment by JeremiahKoeiman** [comment]
Go to your GCP console and add as redirect URL the URL of your backend. This worked for me.

**Comment by brocktubre** [comment]
I am getting the same error:
```
/Users/user/Desktop/Projects/google-sheets-api-integration/index.js:28
      client_id, client_secret, redirect_uris[0]);
                                             ^

TypeError: Cannot read property '0' of undefined
    at authorize (/Users/user/Desktop/Projects/google-sheets-api-integration/index.js:28:46)
    at fs.readFile (/Users/user/Desktop/Projects/google-sheets-api-integration/index.js:16:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
```

I am trying to run the sample application described on the [Node.js Quickstart ](https://developers.google.com/sheets/api/quickstart/nodejs) for Google Sheets API integration. I followed to steps and when I ran the `node .` command to execute the application, I get the error message above.

**Comment by brocktubre** [comment]
I was getting the same error but I solved the issue by selecting a "Desktop app" when running the Quickstart locally, instead of selecting "Web Browser" during **Step 1: Turn on the Google Sheets API**. 

A new credentials.json sheet was downloaded, imported into the project, and solved my problem.

**Comment by adongu** [comment]
@shaikh-amaan-fm  mentioned above, the object property "installed" inside credentials.json is no longer valid and has changed to "web" instead.
Change line 27 from: 
```const { client_secret, client_id, redirect_uris } = credentials.installed;```
to 
```const { client_secret, client_id, redirect_uris } = credentials.web;```

Your code should be working now.  Just follow the direction in the console afterwards.  Make sure you set up a redirect URL after you enable the Gmail API for whichever option you chose, so that you can see the code in the redirect page's query param. Decode that code and you're good to paste that in the console.

**Comment by salmansrabon** [comment]
TypeError: Cannot read property '0' of undefined
    at authorize

**Comment by shaikh-amaan-fm** [comment]
> TypeError: Cannot read property '0' of undefined
>     at authorize 

Elobrate your issue

**Comment by spidyhackx** [comment]
@shaikh-amaan-fm after correcting ".installed" to ".web",it produces another error.
```/home/spidy/Desktop/SpidySys./sheetsApi/server.js:31
      client_id, client_secret, redirect_uris[0]);
                                             ^

TypeError: Cannot read property '0' of undefined
    at authorize (/home/spidy/Desktop/SpidySys./sheetsApi/server.js:31:46)
    at fs.readFile (/home/spidy/Desktop/SpidySys./sheetsApi/server.js:19:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)

```

**Comment by shaikh-amaan-fm** [comment]
> @shaikh-amaan-fm after correcting ".installed" to ".web",it produces another error.
> ```/home/spidy/Desktop/SpidySys./sheetsApi/server.js:31
>       client_id, client_secret, redirect_uris[0]);
>                                              ^
> 
> TypeError: Cannot read property '0' of undefined
>     at authorize (/home/spidy/Desktop/SpidySys./sheetsApi/server.js:31:46)
>     at fs.readFile (/home/spidy/Desktop/SpidySys./sheetsApi/server.js:19:3)
>     at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
> 
> ```

I think at the time of creating credentials.json, you didn't put any redirect URI. Create credentials.json file again from developers comsole and add a redirect URI.

**Comment by spidyhackx** [comment]
thanks bud,it worked

**Comment by edy527** [comment]
> Recibí el mismo error, pero resolví el problema seleccionando una "Aplicación de escritorio" al ejecutar el Inicio rápido localmente, en lugar de seleccionar "Navegador web" durante el **Paso 1: Activar la API de Google Sheets** .
> 
> Se descargó una nueva hoja de credentials.json, se importó al proyecto y resolvió mi problema.

desde las 13hs con este problema y lo solucione gracias a vos. te amo

**Comment by vela91** [comment]
i have the same issue, and error is the same if change to ".web", I can't change to desktop app

**Comment by vela91** [comment]
TypeError: Cannot destructure property 'client_secret' of 'credentials.web' as it is undefined.
    at authorize (/home/vela/Documents/Work/CRM/crm-321-backend/dist/analyticReport.js:40:5)
    at /home/vela/Documents/Work/CRM/crm-321-backend/dist/analyticReport.js:29:3
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)
error Command failed with exit code 1.

**Comment by shaikh-amaan-fm** [comment]
You can inspect the credentials json file and get an idea about the error. I would have helped you in it but you have to share credential.json file and the code in question but sharing credentials json file online wouldn't be a good thing, unless it's a testing one

**Comment by vela91** [comment]
> You can inspect the credentials json file and get an idea about the error. I would have helped you in it but you have to share credential.json file and the code in question but sharing credentials json file online wouldn't be a good thing, unless it's a testing one

I find this and fix my issue, thanks anyway 
=====================================================================
I was having the same issue...not sure if this is the "best" solution...but it works.

• delete
const {client_secret, client_id, redirect_uris} = credentials.installed;

• replace with:
var client_secret = credentials.client_secret; var client_id = credentials.client_id; var redirect_uris = credentials.redirect_uris;

• resulting in the following authorize function:
`function authorize(credentials, callback) {
var client_secret = credentials.client_secret;
var client_id = credentials.client_id;
var redirect_uris = credentials.redirect_uris;

const oAuth2Client = new google.auth.OAuth2(
client_id, client_secret, redirect_uris);

// Check if we have previously stored a token.
fs.readFile(TOKEN_PATH, (err, token) => {
if (err) return getAccessToken(oAuth2Client, callback);
oAuth2Client.setCredentials(JSON.parse(token));
callback(oAuth2Client);
});
}`
